name: CI
on:
  - push
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop
      - run: nix flake check
      - run: |
          nix develop --command \
            mix deps.get
      - run: |
          nix develop --command \
            mix compile --warnings-as-errors
      - run: |
          nix develop --command \
            mix test --trace

  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop
      - run: nix flake check
      - run: |
          nix develop --command \
            mix deps.get
      - run: |
          nix develop --command \
            mix compile --warnings-as-errors
      - run: |
          nix develop --command \
            mix test --trace
